name: Test smart contract

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: cd smart_contract | npm ci

    - name: Run Tests
      run: cd smart_contract | npm test
